language: node_js
node_js:
- '6'

script:
- yarn test
- yarn run lint
- yarn run flow
- yarn run build

# Deploy to gh-pages
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages --force -e; fi

env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: nobody@nobody.org
  - GITHUB_REPO: rstacruz/flowloop
  - GIT_SOURCE: public
  - GIT_BRANCH: gh-pages
